# This file should be placed in a folder named ".streamlit" in your project's root directory.
# .streamlit/config.toml

[theme]
# The color of interactive elements like buttons and links
primaryColor="#ff4b4b"

# The main background color of the app
backgroundColor="#ffffff"

# The background color of the sidebar
secondaryBackgroundColor="#f0f2f6"

# The color of the text
textColor="#31333F"

# The font for the app
font="Inter"
